language: python
python:
    - 3.8

before_install:
  - pip install poetry
  - sudo apt-get update
  - sudo apt-get install unixodbc unixodbc-dev

install:
  - poetry install

script:
  - poetry run flake8 trek tests
  - poetry run coverage run --source=trek -m unittest discover -b

before_deploy:
